'use client';

import { createClient } from '@/lib/supabase/client';

// ─── Types ────────────────────────────────────────────────────────────────────

export type ValuationFlagType =
  | 'overdue_valuation' |'market_unavailable' |'theoretical_pricing_required' |'stale_valuation' |'no_market_data';

export type ValuationFlagStatus = 'open' | 'acknowledged' | 'resolved' | 'suppressed';
export type ValuationFlagSeverity = 'low' | 'medium' | 'high' | 'critical';
export type PricingMethod = 'market_value' | 'theoretical' | 'forced_sale' | 'desktop_estimate' | 'book_value';

export interface ValuationPricingFlag {
  id: string;
  collateralId: string;
  valuationId: string | null;
  flagType: ValuationFlagType;
  flagStatus: ValuationFlagStatus;
  severity: ValuationFlagSeverity;
  title: string;
  description: string | null;
  daysOverdue: number;
  lastValuationDate: string | null;
  nextValuationDue: string | null;
  currentLtv: number | null;
  theoreticalValue: number | null;
  marketValue: number | null;
  pricingMethodUsed: PricingMethod;
  ltvImpactNote: string | null;
  officerNote: string | null;
  acknowledgedBy: string | null;
  acknowledgedAt: string | null;
  resolvedBy: string | null;
  resolvedAt: string | null;
  resolutionNote: string | null;
  suppressedUntil: string | null;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  // joined
  collateralDescription?: string;
  collateralType?: string;
  acknowledgedByName?: string;
  resolvedByName?: string;
}

export interface ValuationFlagStats {
  total: number;
  open: number;
  acknowledged: number;
  resolved: number;
  critical: number;
  high: number;
  overdueCount: number;
  marketUnavailableCount: number;
  theoreticalPricingCount: number;
}

function rowToFlag(row: any): ValuationPricingFlag {
  return {
    id: row.id,
    collateralId: row.collateral_id,
    valuationId: row.valuation_id,
    flagType: row.flag_type,
    flagStatus: row.flag_status,
    severity: row.severity,
    title: row.title,
    description: row.description,
    daysOverdue: row.days_overdue ?? 0,
    lastValuationDate: row.last_valuation_date,
    nextValuationDue: row.next_valuation_due,
    currentLtv: row.current_ltv != null ? parseFloat(row.current_ltv) : null,
    theoreticalValue: row.theoretical_value != null ? parseFloat(row.theoretical_value) : null,
    marketValue: row.market_value != null ? parseFloat(row.market_value) : null,
    pricingMethodUsed: row.pricing_method_used ?? 'theoretical',
    ltvImpactNote: row.ltv_impact_note,
    officerNote: row.officer_note,
    acknowledgedBy: row.acknowledged_by,
    acknowledgedAt: row.acknowledged_at,
    resolvedBy: row.resolved_by,
    resolvedAt: row.resolved_at,
    resolutionNote: row.resolution_note,
    suppressedUntil: row.suppressed_until,
    autoGenerated: row.auto_generated ?? true,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    collateralDescription: row.collateral_records?.description,
    collateralType: row.collateral_records?.collateral_type,
    acknowledgedByName: row.acknowledged_profile?.full_name,
    resolvedByName: row.resolved_profile?.full_name,
  };
}

// ─── Service Functions ────────────────────────────────────────────────────────

export async function listValuationFlags(filters?: {
  status?: ValuationFlagStatus | 'all';
  severity?: ValuationFlagSeverity | 'all';
  flagType?: ValuationFlagType | 'all';
  collateralId?: string;
}): Promise<ValuationPricingFlag[]> {
  const supabase = createClient();
  let query = supabase
    .from('valuation_pricing_flags')
    .select(`
      *,
      collateral_records(description, collateral_type),
      acknowledged_profile:user_profiles!acknowledged_by(full_name),
      resolved_profile:user_profiles!resolved_by(full_name)
    `)
    .order('created_at', { ascending: false });

  if (filters?.status && filters.status !== 'all') {
    query = query.eq('flag_status', filters.status);
  }
  if (filters?.severity && filters.severity !== 'all') {
    query = query.eq('severity', filters.severity);
  }
  if (filters?.flagType && filters.flagType !== 'all') {
    query = query.eq('flag_type', filters.flagType);
  }
  if (filters?.collateralId) {
    query = query.eq('collateral_id', filters.collateralId);
  }

  const { data, error } = await query;
  if (error) throw error;
  return (data ?? []).map(rowToFlag);
}

export async function getValuationFlagStats(): Promise<ValuationFlagStats> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('valuation_pricing_flags')
    .select('flag_status, severity, flag_type');
  if (error) throw error;
  const rows = data ?? [];
  return {
    total: rows.length,
    open: rows.filter((r) => r.flag_status === 'open').length,
    acknowledged: rows.filter((r) => r.flag_status === 'acknowledged').length,
    resolved: rows.filter((r) => r.flag_status === 'resolved').length,
    critical: rows.filter((r) => r.severity === 'critical').length,
    high: rows.filter((r) => r.severity === 'high').length,
    overdueCount: rows.filter((r) => r.flag_type === 'overdue_valuation').length,
    marketUnavailableCount: rows.filter((r) => r.flag_type === 'market_unavailable' || r.flag_type === 'no_market_data').length,
    theoreticalPricingCount: rows.filter((r) => r.flag_type === 'theoretical_pricing_required').length,
  };
}

export async function acknowledgeFlag(
  id: string,
  userId: string,
  note?: string
): Promise<ValuationPricingFlag> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('valuation_pricing_flags')
    .update({
      flag_status: 'acknowledged',
      acknowledged_by: userId,
      acknowledged_at: new Date().toISOString(),
      officer_note: note ?? null,
    })
    .eq('id', id)
    .select(`
      *,
      collateral_records(description, collateral_type),
      acknowledged_profile:user_profiles!acknowledged_by(full_name),
      resolved_profile:user_profiles!resolved_by(full_name)
    `)
    .single();
  if (error) throw error;
  return rowToFlag(data);
}

export async function resolveFlag(
  id: string,
  userId: string,
  resolutionNote: string
): Promise<ValuationPricingFlag> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('valuation_pricing_flags')
    .update({
      flag_status: 'resolved',
      resolved_by: userId,
      resolved_at: new Date().toISOString(),
      resolution_note: resolutionNote,
    })
    .eq('id', id)
    .select(`
      *,
      collateral_records(description, collateral_type),
      acknowledged_profile:user_profiles!acknowledged_by(full_name),
      resolved_profile:user_profiles!resolved_by(full_name)
    `)
    .single();
  if (error) throw error;
  return rowToFlag(data);
}

export async function suppressFlag(
  id: string,
  userId: string,
  suppressedUntil: string
): Promise<ValuationPricingFlag> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('valuation_pricing_flags')
    .update({
      flag_status: 'suppressed',
      suppressed_until: suppressedUntil,
      suppressed_by: userId,
    })
    .eq('id', id)
    .select(`
      *,
      collateral_records(description, collateral_type),
      acknowledged_profile:user_profiles!acknowledged_by(full_name),
      resolved_profile:user_profiles!resolved_by(full_name)
    `)
    .single();
  if (error) throw error;
  return rowToFlag(data);
}

export async function createManualFlag(payload: {
  collateralId: string;
  flagType: ValuationFlagType;
  severity: ValuationFlagSeverity;
  title: string;
  description?: string;
  daysOverdue?: number;
  theoreticalValue?: number;
  pricingMethodUsed?: PricingMethod;
  ltvImpactNote?: string;
  createdBy?: string;
}): Promise<ValuationPricingFlag> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('valuation_pricing_flags')
    .insert({
      collateral_id: payload.collateralId,
      flag_type: payload.flagType,
      severity: payload.severity,
      title: payload.title,
      description: payload.description ?? null,
      days_overdue: payload.daysOverdue ?? 0,
      theoretical_value: payload.theoreticalValue ?? null,
      pricing_method_used: payload.pricingMethodUsed ?? 'theoretical',
      ltv_impact_note: payload.ltvImpactNote ?? null,
      auto_generated: false,
      created_by: payload.createdBy ?? null,
      flag_status: 'open',
    })
    .select(`
      *,
      collateral_records(description, collateral_type),
      acknowledged_profile:user_profiles!acknowledged_by(full_name),
      resolved_profile:user_profiles!resolved_by(full_name)
    `)
    .single();
  if (error) throw error;
  return rowToFlag(data);
}

// ─── Auto-detection: scan overdue valuations and create flags ─────────────────
export async function scanAndCreateOverdueFlags(createdBy?: string): Promise<number> {
  const supabase = createClient();
  const today = new Date().toISOString().split('T')[0];

  // Find overdue valuations not yet flagged
  const { data: overdueValuations, error } = await supabase
    .from('collateral_valuations')
    .select('id, collateral_id, scheduled_date, valuation_status, collateral_records(description)')
    .in('valuation_status', ['Overdue', 'Scheduled'])
    .lt('scheduled_date', today);

  if (error) throw error;
  if (!overdueValuations?.length) return 0;

  let created = 0;
  for (const v of overdueValuations) {
    // Check if open flag already exists for this valuation
    const { data: existing } = await supabase
      .from('valuation_pricing_flags')
      .select('id')
      .eq('valuation_id', v.id)
      .eq('flag_status', 'open')
      .maybeSingle();

    if (existing) continue;

    const daysOverdue = Math.ceil(
      (new Date().getTime() - new Date(v.scheduled_date).getTime()) / (1000 * 60 * 60 * 24)
    );
    const severity: ValuationFlagSeverity =
      daysOverdue > 90 ? 'critical' : daysOverdue > 30 ? 'high' : daysOverdue > 14 ? 'medium' : 'low';

    await supabase.from('valuation_pricing_flags').insert({
      collateral_id: v.collateral_id,
      valuation_id: v.id,
      flag_type: 'overdue_valuation',
      flag_status: 'open',
      severity,
      title: `Valuation Overdue — Theoretical Pricing Active`,
      description: `Scheduled valuation (due ${v.scheduled_date}) has not been completed. LTV is using theoretical pricing.`,
      days_overdue: daysOverdue,
      last_valuation_date: v.scheduled_date,
      pricing_method_used: 'theoretical',
      ltv_impact_note: `LTV may be inaccurate by up to ${Math.min(daysOverdue / 10, 15).toFixed(0)}% due to ${daysOverdue} days without valuation.`,
      auto_generated: true,
      created_by: createdBy ?? null,
    });
    created++;
  }
  return created;
}
