import { serve } from "https://deno.land/std@0.192.0/http/server.ts";

declare const Deno: {
  env: {
    get(key: string): string | undefined;
  };
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers": "*",
      },
    });
  }

  try {
    const { to, subject, reportType, reportLabel, reportSummary, period } = await req.json();

    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) {
      throw new Error("RESEND_API_KEY is not configured");
    }

    const recipients: Array<{ name: string; email: string }> = Array.isArray(to) ? to : [to];

    const summaryRows = reportSummary
      ? Object.entries(reportSummary)
          .map(
            ([k, v]) =>
              `<tr><td style="padding:6px 12px;border-bottom:1px solid #f0f0f0;color:#555;font-size:13px;">${k}</td><td style="padding:6px 12px;border-bottom:1px solid #f0f0f0;font-weight:600;font-size:13px;">${v}</td></tr>`
          )
          .join("")
      : "";

    const htmlBody = `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f5f7fa;font-family:Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f7fa;padding:32px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
        <tr>
          <td style="background:#1e3a5f;padding:24px 32px;">
            <h1 style="margin:0;color:#ffffff;font-size:20px;font-weight:700;">ContentPro Collateral</h1>
            <p style="margin:4px 0 0;color:#a8c4e0;font-size:13px;">Automated Report Delivery</p>
          </td>
        </tr>
        <tr>
          <td style="padding:32px;">
            <h2 style="margin:0 0 8px;color:#1e3a5f;font-size:18px;">${reportLabel}</h2>
            <p style="margin:0 0 24px;color:#666;font-size:14px;">Period: <strong>${period || "Current Period"}</strong></p>
            ${
              summaryRows
                ? `
            <table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e8ecf0;border-radius:6px;overflow:hidden;margin-bottom:24px;">
              <thead>
                <tr style="background:#f8fafc;">
                  <th style="padding:10px 12px;text-align:left;font-size:12px;color:#888;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;">Metric</th>
                  <th style="padding:10px 12px;text-align:left;font-size:12px;color:#888;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;">Value</th>
                </tr>
              </thead>
              <tbody>${summaryRows}</tbody>
            </table>`
                : ""
            }
            <p style="margin:0 0 8px;color:#555;font-size:14px;">This is an automated report generated by the Collateral Management System.</p>
            <p style="margin:0;color:#555;font-size:14px;">Log in to the system for full details and interactive dashboards.</p>
          </td>
        </tr>
        <tr>
          <td style="background:#f8fafc;padding:16px 32px;border-top:1px solid #e8ecf0;">
            <p style="margin:0;color:#999;font-size:12px;">This is an automated message. Please do not reply to this email.</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;

    const sendResults = await Promise.all(
      recipients.map(async (recipient) => {
        const res = await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${RESEND_API_KEY}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            from: "onboarding@resend.dev",
            to: recipient.email,
            subject: subject || `${reportLabel} — ${period || "Automated Report"}`,
            html: htmlBody,
          }),
        });
        const result = await res.json();
        return { email: recipient.email, success: res.ok, result };
      })
    );

    const failed = sendResults.filter((r) => !r.success);

    return new Response(
      JSON.stringify({
        success: failed.length === 0,
        sent: sendResults.filter((r) => r.success).length,
        failed: failed.length,
        results: sendResults,
      }),
      {
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
      }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
      }
    );
  }
});
