import { NextRequest, NextResponse } from 'next/server';
// @ts-ignore
import jsPDF from 'jspdf';
// @ts-ignore
import autoTable from 'jspdf-autotable';

// ─── Types ────────────────────────────────────────────────────────────────────

interface AuditReportRequest {
  dateFrom: string;
  dateTo: string;
  fraudAlerts: any[];
  ruleViolations: any[];
  geoCollateral: any[];
  summary: {
    totalFraudAlerts: number;
    highRiskAlerts: number;
    pendingReview: number;
    ruleViolations: number;
    activeViolations: number;
    geoCollateral: number;
    unverifiedLocations: number;
    reportDate: string;
  } | null;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatDate(iso: string): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

function addPageHeader(doc: any, title: string, subtitle: string, pageWidth: number): number {
  doc.setFillColor(26, 58, 92);
  doc.rect(0, 0, pageWidth, 22, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('CollateralMS — EXIM Bank Tanzania', 14, 9);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleString('en-GB')}`, pageWidth - 14, 9, { align: 'right' });

  doc.setTextColor(26, 58, 92);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 34);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(107, 114, 128);
  doc.text(subtitle, 14, 41);

  return 50;
}

function addSummaryBoxes(doc: any, boxes: { label: string; value: string; color?: [number, number, number] }[], startY: number, pageWidth: number): number {
  const boxW = (pageWidth - 28 - (boxes.length - 1) * 4) / boxes.length;
  boxes.forEach((box, i) => {
    const x = 14 + i * (boxW + 4);
    const [r, g, b] = box.color ?? [243, 244, 246];
    doc.setFillColor(r, g, b);
    doc.roundedRect(x, startY, boxW, 18, 2, 2, 'F');
    doc.setTextColor(107, 114, 128);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text(box.label, x + 4, startY + 6);
    doc.setTextColor(26, 58, 92);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(box.value, x + 4, startY + 14);
  });
  return startY + 24;
}

function addFooter(doc: any, pageWidth: number, pageHeight: number) {
  doc.setFillColor(243, 244, 246);
  doc.rect(0, pageHeight - 10, pageWidth, 10, 'F');
  doc.setTextColor(156, 163, 175);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text('CONFIDENTIAL — EXIM Bank Tanzania | Regulatory Audit Report | CollateralMS', 14, pageHeight - 3);
  doc.text(`Page ${doc.internal.getCurrentPageInfo().pageNumber}`, pageWidth - 14, pageHeight - 3, { align: 'right' });
}

function addSectionTitle(doc: any, title: string, y: number): number {
  doc.setFillColor(26, 58, 92);
  doc.rect(14, y, 4, 8, 'F');
  doc.setTextColor(26, 58, 92);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 21, y + 6);
  return y + 12;
}

const alertTypeLabel: Record<string, string> = {
  DUPLICATE_TITLE: 'Duplicate Title',
  IDENTITY_MISMATCH: 'Identity Mismatch',
  VALUATION_ANOMALY: 'Valuation Anomaly',
  EARLY_WARNING: 'Early Warning',
  DOCUMENT_FORGERY: 'Document Forgery',
};

// ─── Route Handler ────────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  try {
    const body: AuditReportRequest = await request.json();
    const { dateFrom, dateTo, fraudAlerts, ruleViolations, geoCollateral, summary } = body;

    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // ── Cover / Summary Page ──────────────────────────────────────────────────
    let y = addPageHeader(
      doc,
      'Regulatory Audit Report',
      `Fraud Alerts · Compliance Rule Violations · Geomapped Collateral  |  Period: ${formatDate(dateFrom)} – ${formatDate(dateTo)}`,
      pageWidth
    );

    // Regulatory metadata box
    doc.setFillColor(239, 246, 255);
    doc.roundedRect(14, y, pageWidth - 28, 14, 2, 2, 'F');
    doc.setTextColor(26, 58, 92);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('EXIM Bank Tanzania  ·  Regulatory Submission  ·  Classification: CONFIDENTIAL', 18, y + 5.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text(`Report Date: ${summary?.reportDate ?? formatDate(new Date().toISOString())}  ·  Generated by CollateralMS`, 18, y + 11);
    y += 20;

    // KPI summary boxes
    if (summary) {
      y = addSummaryBoxes(doc, [
        { label: 'Total Fraud Alerts', value: String(summary.totalFraudAlerts), color: summary.highRiskAlerts > 0 ? [254, 226, 226] : [243, 244, 246] },
        { label: 'High Risk Alerts', value: String(summary.highRiskAlerts), color: [254, 226, 226] },
        { label: 'Pending Review', value: String(summary.pendingReview), color: [254, 243, 199] },
        { label: 'Rule Violations', value: String(summary.ruleViolations), color: [254, 243, 199] },
        { label: 'Blocking Violations', value: String(summary.activeViolations), color: summary.activeViolations > 0 ? [254, 226, 226] : [209, 250, 229] },
        { label: 'Geo Collateral', value: String(summary.geoCollateral) },
        { label: 'Unverified Locations', value: String(summary.unverifiedLocations), color: summary.unverifiedLocations > 0 ? [254, 243, 199] : [209, 250, 229] },
      ], y, pageWidth);
    }

    // ── Section 1: Fraud Alerts ───────────────────────────────────────────────
    y = addSectionTitle(doc, 'Section 1 — AI-Detected Fraud Alerts', y + 4);

    if (fraudAlerts.length === 0) {
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text('No fraud alerts recorded for this period.', 14, y + 6);
      y += 14;
    } else {
      autoTable(doc, {
        startY: y,
        head: [['Alert Type', 'Collateral ID', 'Risk Score', 'Confidence', 'Status', 'Description', 'Detected']],
        body: fraudAlerts.map((a: any) => [
          alertTypeLabel[a.alert_type] ?? a.alert_type,
          a.collateral_id ?? '—',
          `${Number(a.risk_score).toFixed(1)}`,
          `${Number(a.confidence).toFixed(1)}%`,
          a.status?.replace(/_/g, ' ') ?? '—',
          (a.details?.description ?? JSON.stringify(a.details ?? {})).slice(0, 70),
          formatDate(a.created_at),
        ]),
        styles: { fontSize: 7, cellPadding: 2.5 },
        headStyles: { fillColor: [153, 27, 27], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [254, 242, 242] },
        columnStyles: {
          2: { halign: 'center' },
          3: { halign: 'center' },
        },
        margin: { left: 14, right: 14 },
        didDrawPage: () => addFooter(doc, pageWidth, pageHeight),
      });
      y = (doc as any).lastAutoTable.finalY + 8;
    }

    // ── Section 2: Rule Violations ────────────────────────────────────────────
    doc.addPage();
    y = addPageHeader(
      doc,
      'Regulatory Audit Report — Section 2',
      `Compliance Rule Violations  |  Period: ${formatDate(dateFrom)} – ${formatDate(dateTo)}`,
      pageWidth
    );

    y = addSectionTitle(doc, 'Section 2 — Compliance Rule Violations', y);

    if (ruleViolations.length === 0) {
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text('No rule violations recorded for this period.', 14, y + 6);
      y += 14;
    } else {
      // Violation summary by type
      const typeGroups: Record<string, { total: number; blocking: number }> = {};
      ruleViolations.forEach((v: any) => {
        if (!typeGroups[v.ruleType]) typeGroups[v.ruleType] = { total: 0, blocking: 0 };
        typeGroups[v.ruleType].total++;
        if (v.action === 'BLOCK') typeGroups[v.ruleType].blocking++;
      });

      autoTable(doc, {
        startY: y,
        head: [['Rule Type', 'Total Violations', 'Blocking', 'Warnings', 'Compliance Risk']],
        body: Object.entries(typeGroups).map(([type, data]) => [
          type,
          data.total,
          data.blocking,
          data.total - data.blocking,
          data.blocking > 0 ? '⚠ HIGH' : 'MODERATE',
        ]),
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [26, 58, 92], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        margin: { left: 14, right: 14 },
      });

      y = (doc as any).lastAutoTable.finalY + 8;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(26, 58, 92);
      doc.text('Violation Detail Records', 14, y + 4);
      y += 8;

      autoTable(doc, {
        startY: y,
        head: [['Rule Name', 'Type', 'Action', 'Severity', 'Collateral ID', 'Obligor', 'Message', 'Triggered']],
        body: ruleViolations.map((v: any) => [
          v.ruleName,
          v.ruleType,
          v.action,
          v.severity,
          v.collateralId,
          v.obligor,
          v.message.slice(0, 60),
          formatDate(v.triggeredAt),
        ]),
        styles: { fontSize: 7, cellPadding: 2.5 },
        headStyles: { fillColor: [26, 58, 92], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        didDrawPage: () => addFooter(doc, pageWidth, pageHeight),
        margin: { left: 14, right: 14 },
      });
    }

    // ── Section 3: Geomapped Collateral ───────────────────────────────────────
    doc.addPage();
    y = addPageHeader(
      doc,
      'Regulatory Audit Report — Section 3',
      `Geomapped Collateral Locations  |  Period: ${formatDate(dateFrom)} – ${formatDate(dateTo)}`,
      pageWidth
    );

    y = addSectionTitle(doc, 'Section 3 — Geomapped Collateral & Location Verification', y);

    // Geo summary
    const verified = geoCollateral.filter((g: any) => g.verificationStatus === 'VERIFIED').length;
    const unverified = geoCollateral.filter((g: any) => g.verificationStatus === 'UNVERIFIED').length;
    const mismatch = geoCollateral.filter((g: any) => g.verificationStatus === 'MISMATCH').length;

    y = addSummaryBoxes(doc, [
      { label: 'Total Geo Records', value: String(geoCollateral.length) },
      { label: 'Verified', value: String(verified), color: [209, 250, 229] },
      { label: 'Unverified', value: String(unverified), color: [254, 243, 199] },
      { label: 'Address Mismatches', value: String(mismatch), color: mismatch > 0 ? [254, 226, 226] : [209, 250, 229] },
      { label: 'High Risk Zone', value: String(geoCollateral.filter((g: any) => g.riskZone === 'HIGH').length), color: [254, 226, 226] },
    ], y, pageWidth);

    if (geoCollateral.length === 0) {
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text('No geomapped collateral records available.', 14, y + 6);
    } else {
      autoTable(doc, {
        startY: y,
        head: [['Collateral ID', 'Obligor', 'Type', 'Address', 'Coordinates', 'Risk Zone', 'Status', 'Verification']],
        body: geoCollateral.map((g: any) => [
          g.collateralId,
          g.obligor,
          g.type,
          g.address,
          g.coordinates,
          g.riskZone,
          g.status,
          g.verificationStatus,
        ]),
        styles: { fontSize: 7, cellPadding: 2.5 },
        headStyles: { fillColor: [26, 58, 92], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        didDrawPage: () => addFooter(doc, pageWidth, pageHeight),
        margin: { left: 14, right: 14 },
      });
    }

    // ── Final Footer on last page ─────────────────────────────────────────────
    addFooter(doc, pageWidth, pageHeight);

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="audit_report_regulator_${dateStr}.pdf"`,
        'Content-Length': String(pdfBuffer.length),
      },
    });
  } catch (err: any) {
    console.error('Audit report PDF generation error:', err);
    return NextResponse.json({ error: 'PDF generation failed', details: err.message }, { status: 500 });
  }
}
