export type CollateralStatus =
  | 'Draft' |'Submitted' |'Under Review' |'Perfected' |'Monitoring' |'Released' |'Overdue' |'Rejected';

export type CollateralType =
  | 'Mortgage' |'Debenture' |'Motor Vehicle' |'Shares (DSE)' |'FDR' |'Guarantee' |'Ship/Vessel';

export type RegistryType =
  | 'BRELA' |'Lands Registry' |'TRA' |'DSE' |'TASAC' |'N/A';

export interface Collateral {
  id: string;
  obligor: string;
  obligorId: string;
  type: CollateralType;
  description: string;
  valueTSh: string;
  facilityId: string;
  status: CollateralStatus;
  registry: RegistryType;
  registrationDate: string;
  perfectionDeadline: string;
  assignedOfficer: string;
  requiresPerfection: boolean;
  daysToDeadline: number | null;
}

// Backend integration point: GET /api/collateral?page=1&limit=20
export const mockCollateral: Collateral[] = [
  {
    id: 'col-0312',
    obligor: 'Coastal Traders Co.',
    obligorId: 'OBL-2024-0441',
    type: 'Mortgage',
    description: 'Plot 245, Block D, Kinondoni, Dar es Salaam — Title Deed Vol. 18 Folio 99',
    valueTSh: '780,000,000',
    facilityId: 'TZ-FAC-2025-0441',
    status: 'Under Review',
    registry: 'Lands Registry',
    registrationDate: '14 Apr 2026',
    perfectionDeadline: '26 May 2026',
    assignedOfficer: 'Lisa Alkado',
    requiresPerfection: true,
    daysToDeadline: 31,
  },
  {
    id: 'col-0311',
    obligor: 'Arusha Coffee Growers',
    obligorId: 'OBL-2023-0812',
    type: 'FDR',
    description: 'Fixed Deposit Receipt — EXIM Bank, Account No. 0180-003-44821, 12-month tenor',
    valueTSh: '420,000,000',
    facilityId: 'TZ-FAC-2025-0388',
    status: 'Perfected',
    registry: 'N/A',
    registrationDate: '10 Apr 2026',
    perfectionDeadline: '',
    assignedOfficer: 'Godfrey Woiso',
    requiresPerfection: false,
    daysToDeadline: null,
  },
  {
    id: 'col-0310',
    obligor: 'Dodoma Real Estate Ltd',
    obligorId: 'OBL-2022-0334',
    type: 'Mortgage',
    description: 'Plot 88, Chamwino District, Dodoma — Title Deed Vol. 7 Folio 22',
    valueTSh: '1,250,000,000',
    facilityId: 'TZ-FAC-2024-1021',
    status: 'Perfected',
    registry: 'Lands Registry',
    registrationDate: '02 Mar 2026',
    perfectionDeadline: '13 Apr 2026',
    assignedOfficer: 'Cornel Mangulu',
    requiresPerfection: true,
    daysToDeadline: null,
  },
  {
    id: 'col-0309',
    obligor: 'Mbeya Mining Corp.',
    obligorId: 'OBL-2023-1107',
    type: 'Debenture',
    description: 'Fixed & Floating Charge over all assets — registered at BRELA',
    valueTSh: '8,400,000,000',
    facilityId: 'TZ-FAC-2024-0771',
    status: 'Perfected',
    registry: 'BRELA',
    registrationDate: '15 Feb 2026',
    perfectionDeadline: '29 Mar 2026',
    assignedOfficer: 'Cornel Mangulu',
    requiresPerfection: true,
    daysToDeadline: null,
  },
  {
    id: 'col-0308',
    obligor: 'Kilimanjaro Logistics',
    obligorId: 'OBL-2024-0229',
    type: 'Motor Vehicle',
    description: '2023 Volvo FH16 Truck — Reg. T 112 DXB · Chassis No. YV2RT40A4PA123456',
    valueTSh: '185,000,000',
    facilityId: 'TZ-FAC-2024-0889',
    status: 'Monitoring',
    registry: 'TRA',
    registrationDate: '28 Jan 2026',
    perfectionDeadline: '11 Mar 2026',
    assignedOfficer: 'Yahaya Frezier',
    requiresPerfection: true,
    daysToDeadline: null,
  },
  {
    id: 'col-0307',
    obligor: 'DSE Listed Holdings Ltd',
    obligorId: 'OBL-2023-0594',
    type: 'Shares (DSE)',
    description: '4,200,000 ordinary shares in CRDB Bank PLC — DSE Listed, pledged in favor of EXIM',
    valueTSh: '2,940,000,000',
    facilityId: 'TZ-FAC-2024-0612',
    status: 'Submitted',
    registry: 'DSE',
    registrationDate: '18 Apr 2026',
    perfectionDeadline: '30 May 2026',
    assignedOfficer: 'Lisa Alkado',
    requiresPerfection: true,
    daysToDeadline: 35,
  },
  {
    id: 'col-0306',
    obligor: 'Zanzibar Tourism Group',
    obligorId: 'OBL-2022-0878',
    type: 'Guarantee',
    description: 'Corporate Guarantee from ZTG Holdings Ltd — unlimited in amount',
    valueTSh: '3,200,000,000',
    facilityId: 'TZ-FAC-2024-0503',
    status: 'Perfected',
    registry: 'N/A',
    registrationDate: '05 Dec 2025',
    perfectionDeadline: '',
    assignedOfficer: 'Godfrey Woiso',
    requiresPerfection: false,
    daysToDeadline: null,
  },
  {
    id: 'col-0305',
    obligor: 'Tanga Steel Mills',
    obligorId: 'OBL-2023-0712',
    type: 'Shares (DSE)',
    description: '1,800,000 shares in Tanzania Breweries Ltd — DSE pledge lodged',
    valueTSh: '2,100,000,000',
    facilityId: 'TZ-FAC-2025-0388',
    status: 'Submitted',
    registry: 'DSE',
    registrationDate: '20 Apr 2026',
    perfectionDeadline: '01 Jun 2026',
    assignedOfficer: 'Lisa Alkado',
    requiresPerfection: true,
    daysToDeadline: 37,
  },
  {
    id: 'col-0103',
    obligor: 'Zanzibar Spice Exports',
    obligorId: 'OBL-2024-0099',
    type: 'Ship/Vessel',
    description: 'MV Spice Trader — IMO 9812344, 1,200 DWT, registered at TASAC Zanzibar',
    valueTSh: '6,700,000,000',
    facilityId: 'TZ-FAC-2025-0211',
    status: 'Overdue',
    registry: 'TASAC',
    registrationDate: '22 Mar 2026',
    perfectionDeadline: '22 Apr 2026',
    assignedOfficer: 'Godfrey Woiso',
    requiresPerfection: true,
    daysToDeadline: -3,
  },
  {
    id: 'col-0091',
    obligor: 'Dar Transport Holdings',
    obligorId: 'OBL-2024-0155',
    type: 'Motor Vehicle',
    description: '2022 Mercedes-Benz Actros 2645 · Reg. T 880 CFX · Chassis No. WDB9634031L521987',
    valueTSh: '320,000,000',
    facilityId: 'TZ-FAC-2025-0034',
    status: 'Overdue',
    registry: 'TRA',
    registrationDate: '20 Mar 2026',
    perfectionDeadline: '20 Apr 2026',
    assignedOfficer: 'Lisa Alkado',
    requiresPerfection: true,
    daysToDeadline: -5,
  },
  {
    id: 'col-0078',
    obligor: 'Mwanza Fishing Co.',
    obligorId: 'OBL-2023-0488',
    type: 'Mortgage',
    description: 'Plot 14, Ilemela District, Mwanza — Title Deed Vol. 3 Folio 7',
    valueTSh: '1,800,000,000',
    facilityId: 'TZ-FAC-2024-1104',
    status: 'Overdue',
    registry: 'Lands Registry',
    registrationDate: '18 Mar 2026',
    perfectionDeadline: '18 Apr 2026',
    assignedOfficer: 'Yahaya Frezier',
    requiresPerfection: true,
    daysToDeadline: -7,
  },
  {
    id: 'col-0041',
    obligor: 'Karibu Enterprises Ltd',
    obligorId: 'OBL-2022-0211',
    type: 'Debenture',
    description: 'Fixed Charge over land & buildings + floating charge over all other assets',
    valueTSh: '4,200,000,000',
    facilityId: 'TZ-FAC-2024-0892',
    status: 'Overdue',
    registry: 'BRELA',
    registrationDate: '01 Mar 2026',
    perfectionDeadline: '13 Apr 2026',
    assignedOfficer: 'Lisa Alkado',
    requiresPerfection: true,
    daysToDeadline: -12,
  },
];